[package]
name = "storage"
version = "0.1.2"
authors = ["FindoraNetwork"]
edition = "2018"

[dependencies]
ruc = "1.0"
fmerk = { git = "https://github.com/FindoraNetwork/fmerk.git", tag = "v0.1.1a" }
parking_lot = "0.11.1"
serde = "1.0.124"
serde_json = "1.0.64"
rand = "0.8.3"
