[package]
name = "mem_db"
version = "0.2.0"
authors = ["FindoraNetwork"]
edition = "2021"

[dependencies]
bincode = "1.3"
ruc = "1.0"
serde = { version = "1.0", features = ["derive"] }
storage = { path = "../storage", version = "0.2" }

[features]
iterator = ["storage/iterator"]
